/**
 * Server component: injects Google Dataset structured data (JSON-LD)
 * into the page <head> via Next.js's built-in <script> support.
 *
 * @see https://developers.google.com/search/docs/appearance/structured-data/dataset
 */

const BASE_URL = "https://www.homecastr.com"

interface DatasetJsonLdProps {
    /** e.g. "Texas Home Price Forecasts" */
    name: string
    /** e.g. "Neighborhood-level home price forecasts for counties in Texas." */
    description: string
    /** Canonical path, e.g. "/forecasts/tx" */
    path: string
    /** e.g. "Texas, United States" */
    geographyCovered: string
    /** Query string for the download API, e.g. "state=tx" or "" for national */
    downloadQuery?: string
}

export function DatasetJsonLd({
    name,
    description,
    path,
    geographyCovered,
    downloadQuery,
}: DatasetJsonLdProps) {
    const canonicalUrl = `${BASE_URL}${path}`
    const downloadUrl = downloadQuery
        ? `${BASE_URL}/api/forecasts/download?${downloadQuery}`
        : `${BASE_URL}/api/forecasts/download`

    const today = new Date().toISOString().split("T")[0]

    const jsonLd = {
        "@context": "https://schema.org",
        "@type": "Dataset",
        name,
        description,
        url: canonicalUrl,
        identifier: canonicalUrl,
        license: "https://creativecommons.org/licenses/by/4.0/",
        dateModified: today,
        temporalCoverage: `${today}/..`,
        creator: {
            "@type": "Organization",
            name: "Homecastr",
            url: BASE_URL,
        },
        spatialCoverage: {
            "@type": "Place",
            name: geographyCovered,
        },
        distribution: [
            {
                "@type": "DataDownload",
                encodingFormat: "text/csv",
                contentUrl: downloadUrl,
            },
        ],
        measurementTechnique:
            "Probabilistic machine-learning forecasts generated by the Homecastr World Model (Schrödinger Bridge v12).",
        variableMeasured: [
            {
                "@type": "PropertyValue",
                name: "Median Home Value",
                unitText: "USD",
            },
            {
                "@type": "PropertyValue",
                name: "5-Year Price Appreciation Outlook",
                unitText: "percent",
            },
        ],
    }

    return (
        <script
            type="application/ld+json"
            dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
        />
    )
}
